#!/usr/bin/env bash
# This script installs NGINX on the machine and
# and makes it return the string "Hello World!"
# when queried with a GET request.
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx restart
