#!/usr/bin/env bash
# This script configures a server to be running NGINX and listening on
# port 80 of all the server's active IPV4 IPs.
sudo apt-get update
sudo apt-get install -y nginx
sudo sed "s/listen 80 default_server;/listen 80;/" /etc/nginx/sites-available/default
sudo service nginx restart
