#!/usr/bin/env bash
# This script makes sure the nginx server is listening to port 80 without the service running.
sudo rm /etc/nginx/sites-enables/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart