#!/usr/bin/env bash
# This script configures the container to fit the above requirements
service nginx stop
chmod u+rw /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
service nginx start
